name: ci

permissions:
  contents: write

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
        with:
          go-version: 1.18

      - uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go mod download

      - run: go fmt ./...
      - run: go vet .
      - run: go build -v .

      - run: go test -v -cover ./...
        env:
          TF_ACC: '1'
