name: Release Binaries

permissions:
  # Allows us write to the repo
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Ockam tag to update terrform version to. e.g. ockam_v0.59.0
        required: true

jobs:
  # Should be ran after Pull request has been merged
  create_release:
    name: Create Release
    runs-on: ubuntu-20.04
    environment: release
    steps:
      - uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
        with:
          go-version: 1.18

      - name: Create Release Context
        id: release
        run: |
          tag_name="${{ github.event.inputs.tag }}"
          version=${tag_name:6}

          echo ::set-output name=version::$version

      - name: Checkout Terraform Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
          ref: ${{ steps.release.outputs.version }}

      - name: Import GPG key
        uses: build-trust/.github/actions/import_gpg@custom-actions
        id: release_gpg
        with:
          gpg_private_key: '${{ secrets.RELEASE_GPG_PRIVATE_KEY }}'
          gpg_password: '${{ secrets.RELEASE_GPG_PASSPHRASE }}'
          gpg_name: '${{ secrets.RELEASE_BOT_GITHUB_USERNAME }}'
          gpg_email: '${{ secrets.RELEASE_BOT_EMAIL }}'

      - uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - run: go mod download

      - uses: goreleaser/goreleaser-action@8f67e590f2d095516493f017008adc464e63adb1 # v2.9.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.release_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
